name: bash job

on:
  push:
    branches: ["*"]

jobs:
  bash-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: bash script
        env:
          SS: ${{secrets.MY_SECRET_KEY}}
        run: |
          npm i
          echo ${{secrets.MY_SECRET_KEY}}
          echo $SS
